python minimax_pgd_perturbation.py \
    --arch resnet18 \
    --dataset cifar10 \
    --train-steps 40000 \
    --batch-size 128 \
    --optim sgd \
    --lr 0.1 \
    --lr-decay-rate 0.1 \
    --lr-decay-freq 15000 \
    --weight-decay 5e-4 \
    --momentum 0.9 \
    --atk-pgd-radius 4 \
    --atk-pgd-steps 10 \
    --atk-pgd-step-size 0.8 \
    --atk-pgd-random-start \
    --pgd-radius 8 \
    --pgd-steps 10 \
    --pgd-step-size 1.6 \
    --pgd-random-start \
    --perturb-freq 10 \
    --report-freq 1000 \
    --save-freq 20000 \
    --save-dir ./exp_data/cifar10/mm-perb \
    --save-name mm-perb
