python perturbation.py \
    --arch resnet18 \
    --dataset cifar10 \
    --train-steps 40000 \
    --batch-size 128 \
    --optim sgd \
    --lr 0.1 \
    --lr-decay-rate 0.1 \
    --lr-decay-freq 15000 \
    --weight-decay 5e-4 \
    --momentum 0.9 \
    --pgd-radius 8 \
    --pgd-steps 8 \
    --pgd-step-size 2 \
    --pgd-random-start \
    --pgd-norm-type l-infty \
    --perturb-freq 10 \
    --report-freq 1000 \
    --save-freq 20000 \
    --save-dir ./exp_data/cifar10/perturb \
    --save-name perturb
